name: CI

on:
  push:
    branches:
      - "next"
  pull_request:
    branches:
      - "next"

jobs:
  lint(platform):
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./packages/electron
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint

  build(platform):
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./packages/electron
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
